apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    datafabrikken.service: datafabrikken-cms-service
  name: datafabrikken-cms-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      datafabrikken.service: datafabrikken-cms-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        datafabrikken.service: datafabrikken-cms-service
    spec:
      containers:
      - env:
        - name: ENABLE_IAP
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: ENABLE_IAP
        - name: BASE_URI
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: BASE_URI        
        - name: NAMESPACE
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: PORT
        - name: POSTGRES_NAME
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: POSTGRES_DB_NAME
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: ADMIN_JWT_SECRET
        - name: APP_KEYS
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: APP_KEYS      
        - name: CONNECTION
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: CONNECTION
        - name: POSTGRES_SSL_SELF
          valueFrom:
            secretKeyRef:
              name: datafabrikken-cms-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: POSTGRES_SSL_SELF
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: PASSWORD        
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: datafabrikken-cms-service
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value DATAFABRIKKEN_CMS_SERVICE_MEMORY" .Values.DATAFABRIKKEN_CMS_SERVICE_MEMORY | quote }}
        volumeMounts:
          - mountPath: /app/public/uploads
            name: datafabrikken-cms-service-claim0
      volumes:
        - name: datafabrikken-cms-service-claim0
          persistentVolumeClaim:
            claimName: datafabrikken-cms-service-claim0
      restartPolicy: Always
status: {}
