apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    datafabrikken.service: datafabrikken-portal
  name: datafabrikken-portal
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      datafabrikken.service: datafabrikken-portal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        datafabrikken.service: datafabrikken-portal
    spec:
      containers:
      - env:
        - name: CONTAINER_IMAGE
          value: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        name: datafabrikken-portal
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value DATAFABRIKKEN_PORTAL_MEMORY" .Values.DATAFABRIKKEN_PORTAL_MEMORY | quote }}
      restartPolicy: Always
status: {}
