apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    datafabrikken.service: datafabrikken-veiviser-dele-data
  name: datafabrikken-veiviser-dele-data
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      datafabrikken.service: datafabrikken-veiviser-dele-data
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        datafabrikken.service: datafabrikken-veiviser-dele-data
    spec:
      containers:
      - name: datafabrikken-veiviser-dele-data
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value DATAFABRIKKEN_VEIVISER_DELE_DATA_MEMORY" .Values.DATAFABRIKKEN_VEIVISER_DELE_DATA_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
status: {}
