apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    datafabrikken.service: datafabrikken-portal-nextjs
  name: datafabrikken-portal-nextjs
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    datafabrikken.service: datafabrikken-portal-nextjs
status:
  loadBalancer: {}